### ISSUE TITLE
Support adding only to test sourceSet

### ISSUE THREAD

**Issue by robzienert** [nebula-plugins/nebula-kotlin-plugin#32]
Nebula currently forces Kotlin into the `implementation` scope, but I would like the ability to write my tests in Kotlin, but not ship Kotlin dependencies to library consumers.

**Comment by rpalcolea** [comment]
13.60 now ships with a `nebula.kotlin-nodep` plugin: https://plugins.gradle.org/plugin/nebula.kotlin-nodep which doesn't add `stdlib` to any configuration

In addition to this, the `nebula.kotlin` plugin can now be configured to set the default configuration to add `stdlib` via:

```
nebulaKotlin {
            stdlibConfiguration = "myConfig"
}
``` 

More details on https://github.com/nebula-plugins/nebula-kotlin-plugin/pull/34/files
