### ISSUE TITLE
no dependency in configuration "testFixturesImplementation" added

### ISSUE THREAD

**Issue by tmohme-hypoport** [nebula-plugins/nebula-kotlin-plugin#35]
The 1.3.60 version of the plugin switched from adding the kotlin-stdlib dependency to the "compile" configuration to adding the dependency to the "implementation" configuration.

Although with 1.3.60 the configuration to add the dependency to can be overwritten, it is not desirable to use the outdated "compile" configuration (inherited by "implementation" and "testFixturesImplementation") any longer.
On the other side, only one "stdlibConfiguration" can be specified in the NebulaKotlinExtension.
It would be highly desirable that either

- the plugin adds the kotlin-stdlib dependency also to the "testFixturesImplementation" configuration if present

or 

- the plugin can be configured with multiple configurations to add the dependency to

**Comment by rpalcolea** [comment]
This is done in https://github.com/nebula-plugins/nebula-kotlin-plugin/pull/36

And will be released in the next version of the plugin

**Comment by rpalcolea** [comment]
Hi @tmohme-hypoport, this is now released with `1.3.61`

**Comment by tmohme-hypoport** [comment]
Hi @rpalcolea, 
works like a charm, thx! :)
Just one hint: We are using kotlin build scripts and I made the naive failure to try using an array literal as argument for setting "stdlibConfigurations".
Unfortunately the message you get from gradle in this case is not very helpful and it took me some time to find the solution :(
So, to spare other plugin-users this experience an additonal Kotlin-sample in the README.md (like the one below) would be helpful:

```
nebulaKotlin {
  stdlibConfigurations.set(listOf("implementation", "testFixturesImplementation"))
}
```

**Comment by rpalcolea** [comment]
Glad it works as expected!

Just added your kotlin example to the reader

Thanks again for the suggestion/feedback
