### ISSUE TITLE
Inconsistent module metadata with Kotlin 1.1.1

### ISSUE THREAD

**Issue by rhencke** [nebula-plugins/nebula-kotlin-plugin#5]
Steps to reproduce:

1) Create a build.gradle file with:
```gradle
plugins {
    id 'nebula.kotlin' version '1.1.1'
} 

repositories {
    mavenCentral()
}
```

2) Run `gradle` or `gradlew`
3) Clear out `~/.gradle`, `~/.m2`, `.gradle`, `build`, other usual suspects, try again, same result.

Result:
```
* What went wrong:
A problem occurred configuring root project 'foo'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.1.1.
     Required by:
         project : > com.netflix.nebula:nebula-kotlin-plugin:1.1.1
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.1.1.
         > inconsistent module metadata found. Descriptor: gradle.plugin.org.jetbrains.kotlin:kotlin-gradle-plugin:1.1.1 Errors: bad group: expected='org.jetbrains.kotlin' found='gradle.plugin.org.jetbrains.kotlin'
```

Expected result:

Same as 1.1.0 - no errors.

Other information:

It looks like there's been a change to `https://plugins.gradle.org/m2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.1.1/kotlin-gradle-plugin-1.1.1.pom`.  The groupId is now `gradle.plugin.org.jetbrains.kotlin` in 1.1.1, whereas in 1.1.0 it was `org.jetbrains.kotlin`?

**Comment by choliver** [comment]
This seems to be ok with 1.1.2.

**Comment by DanielThomas** [comment]
Yeah, the metadata in the plugin portal is broken. We contacted the Gradle folks and JetBrains to ask them to fix that.
